# Generated by Django 4.1 on 2022-09-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_stocks_purchase_price_alter_stocks_today_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
