# Generated by Django 4.1 on 2022-09-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_pass', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=3)),
                ('code', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=50)),
                ('today_price', models.IntegerField()),
                ('yesterday_price', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
