# Generated by Django 4.1 on 2022-09-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='purchase_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='today_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='yesterday_price',
            field=models.FloatField(),
        ),
    ]
